name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file from Secrets
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "DIRECT_URL=${{ secrets.DIRECT_URL }}" >> .env
          echo "STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}" >> .env
          echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> .env
          echo "EMAIL_HOST=${{ secrets.EMAIL_HOST }}" >> .env
          echo "EMAIL_PORT=${{ secrets.EMAIL_PORT }}" >> .env
          echo "EMAIL_USER=${{ secrets.EMAIL_USER }}" >> .env
          echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> .env
          echo "APP_CLOUDINARY_CLOUD_NAME=${{ secrets.APP_CLOUDINARY_CLOUD_NAME }}" >> .env
          echo "APP_CLOUDINARY_API_KEY=${{ secrets.APP_CLOUDINARY_API_KEY }}" >> .env
          echo "APP_CLOUDINARY_SECRET_KEY=${{ secrets.APP_CLOUDINARY_SECRET_KEY }}" >> .env
          echo "APP_STRIPE_CANCEL_URL=${{ secrets.APP_STRIPE_CANCEL_URL }}" >> .env
          echo "APP_STRIPE_SUCESS_URL=${{ secrets.APP_STRIPE_SUCESS_URL }}" >> .env
          echo "APP_STRIPE_HOME_URL=${{ secrets.APP_STRIPE_HOME_URL }}" >> .env
          echo "ADMIN_EMAIL=${{ secrets.ADMIN_EMAIL }}" >> .env
          echo "ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }}" >> .env
          echo "WAREHOUSE_STATE=${{ secrets.WAREHOUSE_STATE }}" >> .env

      - name: Copy project files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "."
          target: "~/app"

      - name: Deploy on EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/app
            # Rebuild and restart containers
            sudo docker compose -f docker-compose.prod.yml up -d --build
            # Clean up old/unused images
            sudo docker image prune -f
